defaults:
    - _self_
    - general : general_default
    - model : discrete_uncon
    - train : train_default
    - dataset : qm9
    - decoarse : decoarse_default
    - reduction : reduction_default

spectral:
  num_features: 2
  normalized_laplacian: True

sign_net:
  hidden_features: 128
  num_layers: 5

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}